version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-$GIT_BRANCH}
      - DOCKER_BUILDKIT=1
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$GIT_BRANCH --cache-from $REPOSITORY_URI:$GIT_BRANCH --build-arg BUILDKIT_INLINE_CACHE=1 .
      - docker tag $REPOSITORY_URI:$GIT_BRANCH $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$GIT_BRANCH
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - appspec.yml
    - scripts/restart-docker-services.sh
  name: "phoenix-docker-$GIT_BRANCH-$(date +%Y-%m-%d)"
  discard-paths: yes

